dist: trusty

language: c

cache:
    - ccache
    - pip

compiler:
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes valac-0.26 libglib2.0-bin
      libglib2.0-dev libsoup2.4-dev libfcgi-dev valadoc ninja-build python3-pip
      # examples
      libjson-glib-dev libmemcached-dev libmarkdown2-dev
    - sudo pip3 install cpp-coveralls sphinx PyYAML meson

before_script:
    - mkdir build && cd build
    - /usr/local/bin/meson.py --enable-gcov ..
    - ninja-build

script:
    - ninja-build test
    - cd ..
    - valadoc --pkg=glib-2.0 --pkg=gio-2.0 --pkg=gio-unix-2.0 --pkg=libsoup-2.4
      --pkg=fcgi --target-glib=2.32 --directory=build/apidocs
      --vapidir=/usr/share/vala-0.26/vapi --vapidir=src/vsgi-fastcgi
      src/**/*.vala

after_success:
    - coveralls --repo-token $COVERALLS_TOKEN --build-root build
                --exclude build/examples --exclude build/tests
    - bash <(curl -s https://codecov.io/bash)
