dist: trusty

language: c

cache:
    - ccache
    - pip

compiler:
    - gcc

env:
    - VALAC=valac-0.26
    - VALAC=valac-0.28
    - VALAC=valac-0.30
    - VALAC=valac-0.32
    - VALAC=valac

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes ${VALAC} libglib2.0-bin
      libglib2.0-dev libsoup2.4-dev libfcgi-dev valadoc python3-pip gcovr
      libgee-0.8-dev libctpl-dev libjson-glib-dev libmemcached-dev
      libmarkdown2-dev liblua5.2-dev
    - sudo pip install sphinx sphinx_rtd_theme PyYAML
    - sudo pip3 install meson==0.31
    - wget https://github.com/ninja-build/ninja/releases/download/v1.5.1/ninja-linux.zip
    - sudo unzip ninja-linux.zip -d /usr/local/bin

before_script:
    - mkdir build
    - meson.py -D b_coverage=true -D enable_docs=true -D enable_examples=true . build
    - ninja -C build -v

script:
    - ninja -C build -v test
    - valadoc --pkg=glib-2.0 --pkg=gio-2.0 --pkg=gio-unix-2.0 --pkg=gmodule-2.0
      --pkg=libsoup-2.4 --pkg=fcgi --pkg=posix --target-glib=2.32
      --directory=build/apidocs --vapidir=/usr/share/${VALAC/valac/vala}/vapi
      --vapidir=src/vsgi/servers src/**/*.vala

after_success:
    - bash <(curl -s https://codecov.io/bash)
