#!/usr/bin/env python

def configure(cfg):
    pass

def build(bld):
    from waflib import Context
    bld.shlib(
        target       = 'vsgi-scgi',
        gir          = 'VsgiScgi-{}'.format(Context.g_module.API_VERSION),
        source       = 'vsgi-scgi.vala',
        use          = 'vsgi vsgi-cgi',
        vala_define  = 'INCLUDE_TYPE_MODULE',
        header_path  = '${INCLUDEDIR}/vsgi',
        install_path = '${LIBDIR}')

    bld(
        rule         = '${G_IR_COMPILER} --output=${TGT} ${SRC}',
        target       = 'VsgiScgi-{}.typelib'.format(Context.g_module.API_VERSION),
        source       = '../vsgi/Vsgi-{0}.gir ../vsgi-cgi/VsgiCgi-{0}.gir VsgiScgi-{0}.gir'.format(Context.g_module.API_VERSION),
        install_path = '${LIBDIR}/girepository-1.0')

    bld(
        features     = 'subst',
        target       = 'vsgi-scgi.pc',
        source       = 'vsgi-scgi.pc.in',
        install_path = '${LIBDIR}/pkgconfig',
        VERSION      = Context.g_module.VERSION,
        API_VERSION  = Context.g_module.API_VERSION)
