#!/usr/bin/env python

def configure(cfg):
    cfg.check_cfg(package='gio-unix-2.0', atleast_version='2.32', uselib_store='GIOUNIX', args='--cflags --libs')

def build(bld):
    from waflib import Context
    bld.shlib(
        packages     = 'gio-unix-2.0',
        target       = 'vsgi-cgi',
        gir          = 'VsgiCgi-{}'.format(Context.g_module.API_VERSION),
        source       = 'vsgi-cgi.vala',
        use          = 'vsgi GIOUNIX',
        header_path  = '${INCLUDEDIR}/vsgi',
        install_path = '${LIBDIR}')

    bld(
        rule         = '${G_IR_COMPILER} --output=${TGT} ${SRC}',
        target       = 'VsgiCgi-{}.typelib'.format(Context.g_module.API_VERSION),
        source       = '../vsgi/Vsgi-{0}.gir VsgiCgi-{0}.gir'.format(Context.g_module.API_VERSION),
        install_path = '${LIBDIR}/girepository-1.0')

    bld(
        features     = 'subst',
        target       = 'vsgi-cgi.pc',
        source       = 'vsgi-cgi.pc.in',
        install_path = '${LIBDIR}/pkgconfig',
        VERSION      = Context.g_module.VERSION,
        API_VERSION  = Context.g_module.API_VERSION)

