#!/usr/bin/env python

def configure(cfg):
    pass

def build(bld):
    from waflib import Context
    bld.shlib(
        target       = 'vsgi-mock',
        gir          = 'VsgiMock-{}'.format(Context.g_module.API_VERSION),
        source       = 'vsgi-mock.vala',
        use          = 'vsgi',
        header_path  = '${INCLUDEDIR}/vsgi',
        install_path = '${LIBDIR}')

    bld(
        rule         = '${G_IR_COMPILER} --output=${TGT} ${SRC}',
        target       = 'VsgiMock-{}.typelib'.format(Context.g_module.API_VERSION),
        source       = '../vsgi/Vsgi-{0}.gir VsgiMock-{0}.gir'.format(Context.g_module.API_VERSION),
        install_path = '${LIBDIR}/girepository-1.0')

    bld(
        features     = 'subst',
        target       = 'vsgi-mock.pc',
        source       = 'vsgi-mock.pc.in',
        install_path = '${LIBDIR}/pkgconfig',
        VERSION      = Context.g_module.VERSION,
        API_VERSION  = Context.g_module.API_VERSION)

